### ISSUE TITLE
Module mapping issues

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#2911]
> error: bundling failed: Error: Unable to resolve module `../../node_modules/react-native/modules/analytics` from `/Users/Drew/dev/aao-react-native/source/init/analytics.js`: The module `../../node_modules/react-native/modules/analytics` could not be found from `/Users/Drew/dev/aao-react-native/source/init/analytics.js`. Indeed, none of these files exist:
>
 > * `/Users/Drew/dev/aao-react-native/node_modules/react-native/modules/analytics(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`
>  * `/Users/Drew/dev/aao-react-native/node_modules/react-native/modules/analytics/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`

**Comment by drewvolz** [comment]
I believe this involves more than just the analytics module. It can't find `api` either.

**Comment by drewvolz** [comment]
This is probably due to the `module-resolver` plugin. Do we need to have a `root` defined?

**Comment by hawkrives** [comment]
No. Plus, it works on CI.

**Comment by hawkrives** [comment]
We don't need a `root` defined because we use the `alias` key, and reference all of our modules via those aliases.

**Comment by hawkrives** [comment]
I would do more debugging, but my system isn't liking React-Native's c++ dependencies again, so I can't even get the native build to finish.

However, running `yarn ios:bundle` passes successfully for me on `master` (903f210885509135e64527406c6bb0807f46e22e)

**Comment by rye** [comment]
I can confirm that `yarn run bundle:android` works fine for me too.

**Comment by drewvolz** [comment]
`yarn run bundle:ios` and `yarn run bundle:android` work for me, too.

**Comment by drewvolz** [comment]
Solved with `yarn start -- --reset-cache`

**Comment by hannesmcman** [comment]
I'm still having this issue...tried `yarn start -- --reset-cache`, re-cloning,  and removing node_modules/ to no avail.

**Comment by hawkrives** [comment]
Ok. 

I have an alternate idea that doesn't require the babel plugin; I'll work on that later this week.

**Comment by drewvolz** [comment]
@hannesmcman have you tried `watchman watch-del-all`

**Comment by hawkrives** [comment]
I should have a new PR up later tonight. I'm moving to either lerna or Yarn's workspaces, I haven't quite decided which yet. Lerna would be nice for publishing these separately, but we may just hold off on that until we split up this repo, so I'm going to play with workspaces some more.

First I'm adding `package.json` files to the modules, and enumerating any interdependencies / fixing the few places that imports from "app" got through (yay, callstack/react-theme-provider.)

**Comment by rye** [comment]
I don't really know if we need to switch away from our current solution. Since it builds in CI, which is a clean environment, and runs perfectly fine for me and @hawkrives locally, I think the broader question is why it's not working for @drewvolz or @hannesmcman.

`watchman watch-del-all` deletes a watcher for my AAO-React-Native directory for me. This should be tested in an environment where the bundle doesn't work. Also, rebooting. I don't know beyond that.

I can also confirm that my built bundles do have the `analytics` and `api` modules present. So I can't reproduce this locally.

**Comment by drewvolz** [comment]
(for what it's worth, @rye, I'm back on track after resetting yarn's cache)

**Comment by hawkrives** [comment]
I think the yarn workspace solution is cleaner, technically speaking, since it doesn't rewrite our import paths dynamically. It's much more statically analyzable, without having to reconfigure things to understand another module resolution scheme.

Plus, it gets us another step closer to having independent packages that we can publish and consume from the app.

**Comment by hannesmcman** [comment]
@drewvolz @rye Yeah I tried resetting yarn's cache and `watchman watch-del-all` and neither worked..

**Comment by hawkrives** [comment]
Closed by #2920

**Comment by hawkrives** [comment]
I hope
